### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by richardhj** [richardhj/contao-notifier-bundle#1]
- [ ] fully compatible with `smyfony/notifier` bundles, e.g., `symfony/sendinblue-notifier`
- [ ] support for HTML-e-mail-Twig-templates with live preview
- [ ] support for flash messages
- [ ] nc_queue is superseded by messenger bus
